language: php

sudo: required

php:
  - 7.1
  - 7.2

env:
  global:
    - setup=basic
    - coverage=no
  matrix:
    - IMAGINE_DRIVER=imagick
    - IMAGINE_DRIVER=gmagick

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true
  - sudo apt-get remove -y imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -y libtiff-dev libjpeg-dev libdjvulibre-dev libwmf-dev pkg-config liblcms2-dev
  - sh -e -c " if [ '$IMAGINE_DRIVER' = 'imagick' ]; then bash ./.travis/imagick.sh; fi"
  - sh -e -c " if [ '$IMAGINE_DRIVER' = 'gmagick' ]; then bash ./.travis/gmagick.sh; fi"
  - phpenv rehash

before_script:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-source --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then travis_retry composer require "satooshi/php-coveralls=~1.0" --prefer-source --no-interaction --dev; fi

script:
  - if [[ $coverage = 'yes' ]]; then ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then ./vendor/bin/phpunit -c phpunit.xml --testdox --verbose; fi

after_script:
  - if [[ $setup = 'coveralls' ]]; then php vendor/bin/coveralls -v; fi

matrix:
  include:
    - php: 7.0
      env: setup=lowest IMAGINE_DRIVER=imagick
    - php: 7.0
      env: setup=lowest IMAGINE_DRIVER=gmagick
    - php: 7.0
      env: setup=stable IMAGINE_DRIVER=imagick
    - php: 7.0
      env: setup=stable IMAGINE_DRIVER=gmagick
    - php: 7.0
      env: setup=coveralls coverage=yes IMAGINE_DRIVER=imagick
  allow_failures:
    - env: setup=coveralls coverage=yes IMAGINE_DRIVER=imagick
  fast_finish: true
