dist: bionic
language: php

php:
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache
    - cache

env:
  global:
    - coverage=no
  matrix:
    - setup=basic IMAGINE_DRIVER=imagick
    - setup=basic IMAGINE_DRIVER=gmagick
    - setup=stable IMAGINE_DRIVER=imagick
    - setup=stable IMAGINE_DRIVER=gmagick
    - setup=lowest IMAGINE_DRIVER=imagick
    - setup=lowest IMAGINE_DRIVER=gmagick

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - composer config discard-changes true

install:
  - sudo apt-get remove -y imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -y libtiff-dev libjpeg-dev libdjvulibre-dev libwmf-dev pkg-config liblcms2-dev
  - if [[ $IMAGINE_DRIVER = imagick ]]; then ./.travis/imagick.sh; fi
  - if [[ $IMAGINE_DRIVER = gmagick ]]; then ./.travis/gmagick.sh; fi
  - phpenv rehash

before_script:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then travis_retry composer require "php-coveralls/php-coveralls=^2.1" --prefer-dist --no-interaction --no-suggest --dev; fi

script:
  - if [[ $coverage = 'yes' ]]; then vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then vendor/bin/phpunit -c phpunit.xml --verbose; fi

after_script:
  - if [[ $setup = 'coveralls' ]]; then php vendor/bin/php-coveralls -v; fi

matrix:
  include:
    - php: 7.3
      env: setup=coveralls coverage=yes IMAGINE_DRIVER=imagick
  allow_failures:
    - php: nightly
    - env: setup=coveralls coverage=yes IMAGINE_DRIVER=imagick
  fast_finish: true
